// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: axon.proto

package axonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FindingType categorizes the security finding.
type FindingType int32

const (
	FindingType_FINDING_TYPE_UNSPECIFIED FindingType = 0
	FindingType_FINDING_TYPE_SAST        FindingType = 1
	FindingType_FINDING_TYPE_DAST        FindingType = 2
	FindingType_FINDING_TYPE_SCA         FindingType = 3
	FindingType_FINDING_TYPE_CLOUD       FindingType = 4
	FindingType_FINDING_TYPE_SECRETS     FindingType = 5
)

// Enum value maps for FindingType.
var (
	FindingType_name = map[int32]string{
		0: "FINDING_TYPE_UNSPECIFIED",
		1: "FINDING_TYPE_SAST",
		2: "FINDING_TYPE_DAST",
		3: "FINDING_TYPE_SCA",
		4: "FINDING_TYPE_CLOUD",
		5: "FINDING_TYPE_SECRETS",
	}
	FindingType_value = map[string]int32{
		"FINDING_TYPE_UNSPECIFIED": 0,
		"FINDING_TYPE_SAST":        1,
		"FINDING_TYPE_DAST":        2,
		"FINDING_TYPE_SCA":         3,
		"FINDING_TYPE_CLOUD":       4,
		"FINDING_TYPE_SECRETS":     5,
	}
)

func (x FindingType) Enum() *FindingType {
	p := new(FindingType)
	*p = x
	return p
}

func (x FindingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindingType) Descriptor() protoreflect.EnumDescriptor {
	return file_axon_proto_enumTypes[0].Descriptor()
}

func (FindingType) Type() protoreflect.EnumType {
	return &file_axon_proto_enumTypes[0]
}

func (x FindingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindingType.Descriptor instead.
func (FindingType) EnumDescriptor() ([]byte, []int) {
	return file_axon_proto_rawDescGZIP(), []int{0}
}

// Severity represents a canonical 0.0-10.0 scale for cross-tool mapping.
type Severity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float32                `protobuf:"fixed32,1,opt,name=score,proto3" json:"score,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Vector        string                 `protobuf:"bytes,3,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Severity) Reset() {
	*x = Severity{}
	mi := &file_axon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Severity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Severity) ProtoMessage() {}

func (x *Severity) ProtoReflect() protoreflect.Message {
	mi := &file_axon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Severity.ProtoReflect.Descriptor instead.
func (*Severity) Descriptor() ([]byte, []int) {
	return file_axon_proto_rawDescGZIP(), []int{0}
}

func (x *Severity) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Severity) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Severity) GetVector() string {
	if x != nil {
		return x.Vector
	}
	return ""
}

// Vulnerability provides detailed metadata about the identified threat.
type Vulnerability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Cwe           []string               `protobuf:"bytes,3,rep,name=cwe,proto3" json:"cwe,omitempty"`
	Aliases       []string               `protobuf:"bytes,4,rep,name=aliases,proto3" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vulnerability) Reset() {
	*x = Vulnerability{}
	mi := &file_axon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vulnerability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vulnerability) ProtoMessage() {}

func (x *Vulnerability) ProtoReflect() protoreflect.Message {
	mi := &file_axon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vulnerability.ProtoReflect.Descriptor instead.
func (*Vulnerability) Descriptor() ([]byte, []int) {
	return file_axon_proto_rawDescGZIP(), []int{1}
}

func (x *Vulnerability) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vulnerability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Vulnerability) GetCwe() []string {
	if x != nil {
		return x.Cwe
	}
	return nil
}

func (x *Vulnerability) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

// Location pinpoint the finding in the target resource.
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	StartLine     int32                  `protobuf:"varint,2,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	StartCol      int32                  `protobuf:"varint,3,opt,name=start_col,json=startCol,proto3" json:"start_col,omitempty"`
	EndLine       int32                  `protobuf:"varint,4,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	EndCol        int32                  `protobuf:"varint,5,opt,name=end_col,json=endCol,proto3" json:"end_col,omitempty"`
	Snippet       string                 `protobuf:"bytes,6,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_axon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_axon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_axon_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Location) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *Location) GetStartCol() int32 {
	if x != nil {
		return x.StartCol
	}
	return 0
}

func (x *Location) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *Location) GetEndCol() int32 {
	if x != nil {
		return x.EndCol
	}
	return 0
}

func (x *Location) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

// Resource identifies the affected component.
type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_axon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_axon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_axon_proto_rawDescGZIP(), []int{3}
}

func (x *Resource) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Evidence is the core IEM struct for axon normalization.
type Evidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Type          FindingType            `protobuf:"varint,3,opt,name=type,proto3,enum=axon.v1.FindingType" json:"type,omitempty"`
	Vulnerability *Vulnerability         `protobuf:"bytes,4,opt,name=vulnerability,proto3" json:"vulnerability,omitempty"`
	Resource      *Resource              `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	Location      *Location              `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Severity      *Severity              `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
	Details       map[string]string      `protobuf:"bytes,8,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_axon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_axon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_axon_proto_rawDescGZIP(), []int{4}
}

func (x *Evidence) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Evidence) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Evidence) GetType() FindingType {
	if x != nil {
		return x.Type
	}
	return FindingType_FINDING_TYPE_UNSPECIFIED
}

func (x *Evidence) GetVulnerability() *Vulnerability {
	if x != nil {
		return x.Vulnerability
	}
	return nil
}

func (x *Evidence) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *Evidence) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Evidence) GetSeverity() *Severity {
	if x != nil {
		return x.Severity
	}
	return nil
}

func (x *Evidence) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Evidence) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// IngestRequest sends a stream of evidence from a runner.
type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evidence      *Evidence              `protobuf:"bytes,1,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_axon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_axon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_axon_proto_rawDescGZIP(), []int{5}
}

func (x *IngestRequest) GetEvidence() *Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

// IngestResponse acknowledges the receipt of evidence.
type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_axon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_axon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_axon_proto_rawDescGZIP(), []int{6}
}

func (x *IngestResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IngestResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_axon_proto protoreflect.FileDescriptor

const file_axon_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"axon.proto\x12\aaxon.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"N\n" +
	"\bSeverity\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x02R\x05score\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x16\n" +
	"\x06vector\x18\x03 \x01(\tR\x06vector\"m\n" +
	"\rVulnerability\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x10\n" +
	"\x03cwe\x18\x03 \x03(\tR\x03cwe\x12\x18\n" +
	"\aaliases\x18\x04 \x03(\tR\aaliases\"\xa8\x01\n" +
	"\bLocation\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"start_line\x18\x02 \x01(\x05R\tstartLine\x12\x1b\n" +
	"\tstart_col\x18\x03 \x01(\x05R\bstartCol\x12\x19\n" +
	"\bend_line\x18\x04 \x01(\x05R\aendLine\x12\x17\n" +
	"\aend_col\x18\x05 \x01(\x05R\x06endCol\x12\x18\n" +
	"\asnippet\x18\x06 \x01(\tR\asnippet\"^\n" +
	"\bResource\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\xdb\x03\n" +
	"\bEvidence\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.axon.v1.FindingTypeR\x04type\x12<\n" +
	"\rvulnerability\x18\x04 \x01(\v2\x16.axon.v1.VulnerabilityR\rvulnerability\x12-\n" +
	"\bresource\x18\x05 \x01(\v2\x11.axon.v1.ResourceR\bresource\x12-\n" +
	"\blocation\x18\x06 \x01(\v2\x11.axon.v1.LocationR\blocation\x12-\n" +
	"\bseverity\x18\a \x01(\v2\x11.axon.v1.SeverityR\bseverity\x128\n" +
	"\adetails\x18\b \x03(\v2\x1e.axon.v1.Evidence.DetailsEntryR\adetails\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\rIngestRequest\x12-\n" +
	"\bevidence\x18\x01 \x01(\v2\x11.axon.v1.EvidenceR\bevidence\"<\n" +
	"\x0eIngestResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted*\xa1\x01\n" +
	"\vFindingType\x12\x1c\n" +
	"\x18FINDING_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FINDING_TYPE_SAST\x10\x01\x12\x15\n" +
	"\x11FINDING_TYPE_DAST\x10\x02\x12\x14\n" +
	"\x10FINDING_TYPE_SCA\x10\x03\x12\x16\n" +
	"\x12FINDING_TYPE_CLOUD\x10\x04\x12\x18\n" +
	"\x14FINDING_TYPE_SECRETS\x10\x052U\n" +
	"\x0eIngressService\x12C\n" +
	"\fIngestStream\x12\x16.axon.v1.IngestRequest\x1a\x17.axon.v1.IngestResponse(\x010\x01B*Z(github.com/axon/axon/api/proto/v1;axonv1b\x06proto3"

var (
	file_axon_proto_rawDescOnce sync.Once
	file_axon_proto_rawDescData []byte
)

func file_axon_proto_rawDescGZIP() []byte {
	file_axon_proto_rawDescOnce.Do(func() {
		file_axon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_axon_proto_rawDesc), len(file_axon_proto_rawDesc)))
	})
	return file_axon_proto_rawDescData
}

var file_axon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_axon_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_axon_proto_goTypes = []any{
	(FindingType)(0),              // 0: axon.v1.FindingType
	(*Severity)(nil),              // 1: axon.v1.Severity
	(*Vulnerability)(nil),         // 2: axon.v1.Vulnerability
	(*Location)(nil),              // 3: axon.v1.Location
	(*Resource)(nil),              // 4: axon.v1.Resource
	(*Evidence)(nil),              // 5: axon.v1.Evidence
	(*IngestRequest)(nil),         // 6: axon.v1.IngestRequest
	(*IngestResponse)(nil),        // 7: axon.v1.IngestResponse
	nil,                           // 8: axon.v1.Evidence.DetailsEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_axon_proto_depIdxs = []int32{
	0, // 0: axon.v1.Evidence.type:type_name -> axon.v1.FindingType
	2, // 1: axon.v1.Evidence.vulnerability:type_name -> axon.v1.Vulnerability
	4, // 2: axon.v1.Evidence.resource:type_name -> axon.v1.Resource
	3, // 3: axon.v1.Evidence.location:type_name -> axon.v1.Location
	1, // 4: axon.v1.Evidence.severity:type_name -> axon.v1.Severity
	8, // 5: axon.v1.Evidence.details:type_name -> axon.v1.Evidence.DetailsEntry
	9, // 6: axon.v1.Evidence.timestamp:type_name -> google.protobuf.Timestamp
	5, // 7: axon.v1.IngestRequest.evidence:type_name -> axon.v1.Evidence
	6, // 8: axon.v1.IngressService.IngestStream:input_type -> axon.v1.IngestRequest
	7, // 9: axon.v1.IngressService.IngestStream:output_type -> axon.v1.IngestResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_axon_proto_init() }
func file_axon_proto_init() {
	if File_axon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_axon_proto_rawDesc), len(file_axon_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_axon_proto_goTypes,
		DependencyIndexes: file_axon_proto_depIdxs,
		EnumInfos:         file_axon_proto_enumTypes,
		MessageInfos:      file_axon_proto_msgTypes,
	}.Build()
	File_axon_proto = out.File
	file_axon_proto_goTypes = nil
	file_axon_proto_depIdxs = nil
}
