// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/axon/v1/evidence.proto

package axonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	GeneratedAt   string                 `protobuf:"bytes,2,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	Source        *SourceDescriptor      `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Summary       *Summary               `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Findings      []*Finding             `protobuf:"bytes,5,rep,name=findings,proto3" json:"findings,omitempty"`
	Correlations  []*RootCauseCluster    `protobuf:"bytes,6,rep,name=correlations,proto3" json:"correlations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *Document) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

func (x *Document) GetSource() *SourceDescriptor {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Document) GetSummary() *Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *Document) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *Document) GetCorrelations() []*RootCauseCluster {
	if x != nil {
		return x.Correlations
	}
	return nil
}

type Summary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalFindings      uint64                 `protobuf:"varint,1,opt,name=total_findings,json=totalFindings,proto3" json:"total_findings,omitempty"`
	UniqueFindings     uint64                 `protobuf:"varint,2,opt,name=unique_findings,json=uniqueFindings,proto3" json:"unique_findings,omitempty"`
	CorrelatedFindings uint64                 `protobuf:"varint,3,opt,name=correlated_findings,json=correlatedFindings,proto3" json:"correlated_findings,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{1}
}

func (x *Summary) GetTotalFindings() uint64 {
	if x != nil {
		return x.TotalFindings
	}
	return 0
}

func (x *Summary) GetUniqueFindings() uint64 {
	if x != nil {
		return x.UniqueFindings
	}
	return 0
}

func (x *Summary) GetCorrelatedFindings() uint64 {
	if x != nil {
		return x.CorrelatedFindings
	}
	return 0
}

type SourceDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolVersion   string                 `protobuf:"bytes,3,opt,name=tool_version,json=toolVersion,proto3" json:"tool_version,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	FormatVersion string                 `protobuf:"bytes,5,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	Uri           string                 `protobuf:"bytes,6,opt,name=uri,proto3" json:"uri,omitempty"`
	GeneratedAt   string                 `protobuf:"bytes,7,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceDescriptor) Reset() {
	*x = SourceDescriptor{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceDescriptor) ProtoMessage() {}

func (x *SourceDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceDescriptor.ProtoReflect.Descriptor instead.
func (*SourceDescriptor) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{2}
}

func (x *SourceDescriptor) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SourceDescriptor) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *SourceDescriptor) GetToolVersion() string {
	if x != nil {
		return x.ToolVersion
	}
	return ""
}

func (x *SourceDescriptor) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *SourceDescriptor) GetFormatVersion() string {
	if x != nil {
		return x.FormatVersion
	}
	return ""
}

func (x *SourceDescriptor) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *SourceDescriptor) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

type Finding struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion     string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Id                string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Kind              string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Title             string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description       string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Severity          *Severity              `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"`
	Confidence        string                 `protobuf:"bytes,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Rule              *Rule                  `protobuf:"bytes,8,opt,name=rule,proto3" json:"rule,omitempty"`
	PrimaryLocation   *Location              `protobuf:"bytes,9,opt,name=primary_location,json=primaryLocation,proto3" json:"primary_location,omitempty"`
	Locations         []*Location            `protobuf:"bytes,10,rep,name=locations,proto3" json:"locations,omitempty"`
	Artifact          *Artifact              `protobuf:"bytes,11,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Package           *Package               `protobuf:"bytes,12,opt,name=package,proto3" json:"package,omitempty"`
	Image             *Image                 `protobuf:"bytes,13,opt,name=image,proto3" json:"image,omitempty"`
	Cloud             *CloudResource         `protobuf:"bytes,14,opt,name=cloud,proto3" json:"cloud,omitempty"`
	Secret            *Secret                `protobuf:"bytes,15,opt,name=secret,proto3" json:"secret,omitempty"`
	Vulnerability     *Vulnerability         `protobuf:"bytes,16,opt,name=vulnerability,proto3" json:"vulnerability,omitempty"`
	References        []*Reference           `protobuf:"bytes,17,rep,name=references,proto3" json:"references,omitempty"`
	Tags              []string               `protobuf:"bytes,18,rep,name=tags,proto3" json:"tags,omitempty"`
	Source            *SourceRecord          `protobuf:"bytes,19,opt,name=source,proto3" json:"source,omitempty"`
	Identity          *Identity              `protobuf:"bytes,20,opt,name=identity,proto3" json:"identity,omitempty"`
	RootCauseHints    []*RootCauseHint       `protobuf:"bytes,21,rep,name=root_cause_hints,json=rootCauseHints,proto3" json:"root_cause_hints,omitempty"`
	Annotations       map[string]string      `protobuf:"bytes,22,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FirstObservedAt   string                 `protobuf:"bytes,23,opt,name=first_observed_at,json=firstObservedAt,proto3" json:"first_observed_at,omitempty"`
	LastObservedAt    string                 `protobuf:"bytes,24,opt,name=last_observed_at,json=lastObservedAt,proto3" json:"last_observed_at,omitempty"`
	RawRecordChecksum string                 `protobuf:"bytes,25,opt,name=raw_record_checksum,json=rawRecordChecksum,proto3" json:"raw_record_checksum,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{3}
}

func (x *Finding) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *Finding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Finding) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Finding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Finding) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Finding) GetSeverity() *Severity {
	if x != nil {
		return x.Severity
	}
	return nil
}

func (x *Finding) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *Finding) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *Finding) GetPrimaryLocation() *Location {
	if x != nil {
		return x.PrimaryLocation
	}
	return nil
}

func (x *Finding) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *Finding) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *Finding) GetPackage() *Package {
	if x != nil {
		return x.Package
	}
	return nil
}

func (x *Finding) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Finding) GetCloud() *CloudResource {
	if x != nil {
		return x.Cloud
	}
	return nil
}

func (x *Finding) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *Finding) GetVulnerability() *Vulnerability {
	if x != nil {
		return x.Vulnerability
	}
	return nil
}

func (x *Finding) GetReferences() []*Reference {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *Finding) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Finding) GetSource() *SourceRecord {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Finding) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Finding) GetRootCauseHints() []*RootCauseHint {
	if x != nil {
		return x.RootCauseHints
	}
	return nil
}

func (x *Finding) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Finding) GetFirstObservedAt() string {
	if x != nil {
		return x.FirstObservedAt
	}
	return ""
}

func (x *Finding) GetLastObservedAt() string {
	if x != nil {
		return x.LastObservedAt
	}
	return ""
}

func (x *Finding) GetRawRecordChecksum() string {
	if x != nil {
		return x.RawRecordChecksum
	}
	return ""
}

type Severity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Vector        string                 `protobuf:"bytes,3,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Severity) Reset() {
	*x = Severity{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Severity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Severity) ProtoMessage() {}

func (x *Severity) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Severity.ProtoReflect.Descriptor instead.
func (*Severity) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{4}
}

func (x *Severity) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Severity) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Severity) GetVector() string {
	if x != nil {
		return x.Vector
	}
	return ""
}

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Subcategory   string                 `protobuf:"bytes,4,opt,name=subcategory,proto3" json:"subcategory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{5}
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Rule) GetSubcategory() string {
	if x != nil {
		return x.Subcategory
	}
	return ""
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Line          uint32                 `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Column        uint32                 `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	EndLine       uint32                 `protobuf:"varint,4,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	EndColumn     uint32                 `protobuf:"varint,5,opt,name=end_column,json=endColumn,proto3" json:"end_column,omitempty"`
	SnippetDigest string                 `protobuf:"bytes,6,opt,name=snippet_digest,json=snippetDigest,proto3" json:"snippet_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{6}
}

func (x *Location) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Location) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Location) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *Location) GetEndLine() uint32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *Location) GetEndColumn() uint32 {
	if x != nil {
		return x.EndColumn
	}
	return 0
}

func (x *Location) GetSnippetDigest() string {
	if x != nil {
		return x.SnippetDigest
	}
	return ""
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{7}
}

func (x *Artifact) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Artifact) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Package struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	FixedVersion    string                 `protobuf:"bytes,4,opt,name=fixed_version,json=fixedVersion,proto3" json:"fixed_version,omitempty"`
	Language        string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	PackageUrl      string                 `protobuf:"bytes,6,opt,name=package_url,json=packageUrl,proto3" json:"package_url,omitempty"`
	DependencyChain []string               `protobuf:"bytes,7,rep,name=dependency_chain,json=dependencyChain,proto3" json:"dependency_chain,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{8}
}

func (x *Package) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Package) GetFixedVersion() string {
	if x != nil {
		return x.FixedVersion
	}
	return ""
}

func (x *Package) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Package) GetPackageUrl() string {
	if x != nil {
		return x.PackageUrl
	}
	return ""
}

func (x *Package) GetDependencyChain() []string {
	if x != nil {
		return x.DependencyChain
	}
	return nil
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registry      string                 `protobuf:"bytes,1,opt,name=registry,proto3" json:"registry,omitempty"`
	Repository    string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Digest        string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	BaseDigest    string                 `protobuf:"bytes,5,opt,name=base_digest,json=baseDigest,proto3" json:"base_digest,omitempty"`
	BaseName      string                 `protobuf:"bytes,6,opt,name=base_name,json=baseName,proto3" json:"base_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{9}
}

func (x *Image) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *Image) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *Image) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Image) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *Image) GetBaseDigest() string {
	if x != nil {
		return x.BaseDigest
	}
	return ""
}

func (x *Image) GetBaseName() string {
	if x != nil {
		return x.BaseName
	}
	return ""
}

type CloudResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Service       string                 `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	ResourceId    string                 `protobuf:"bytes,5,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceArn   string                 `protobuf:"bytes,6,opt,name=resource_arn,json=resourceArn,proto3" json:"resource_arn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudResource) Reset() {
	*x = CloudResource{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudResource) ProtoMessage() {}

func (x *CloudResource) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudResource.ProtoReflect.Descriptor instead.
func (*CloudResource) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{10}
}

func (x *CloudResource) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CloudResource) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CloudResource) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CloudResource) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *CloudResource) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CloudResource) GetResourceArn() string {
	if x != nil {
		return x.ResourceArn
	}
	return ""
}

type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Redacted      string                 `protobuf:"bytes,4,opt,name=redacted,proto3" json:"redacted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{11}
}

func (x *Secret) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Secret) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Secret) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Secret) GetRedacted() string {
	if x != nil {
		return x.Redacted
	}
	return ""
}

type Vulnerability struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Aliases        []string               `protobuf:"bytes,2,rep,name=aliases,proto3" json:"aliases,omitempty"`
	Cwe            []string               `protobuf:"bytes,3,rep,name=cwe,proto3" json:"cwe,omitempty"`
	CvssVector     string                 `protobuf:"bytes,4,opt,name=cvss_vector,json=cvssVector,proto3" json:"cvss_vector,omitempty"`
	CvssScore      float64                `protobuf:"fixed64,5,opt,name=cvss_score,json=cvssScore,proto3" json:"cvss_score,omitempty"`
	AttackVector   string                 `protobuf:"bytes,6,opt,name=attack_vector,json=attackVector,proto3" json:"attack_vector,omitempty"`
	Exploitability string                 `protobuf:"bytes,7,opt,name=exploitability,proto3" json:"exploitability,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Vulnerability) Reset() {
	*x = Vulnerability{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vulnerability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vulnerability) ProtoMessage() {}

func (x *Vulnerability) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vulnerability.ProtoReflect.Descriptor instead.
func (*Vulnerability) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{12}
}

func (x *Vulnerability) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vulnerability) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *Vulnerability) GetCwe() []string {
	if x != nil {
		return x.Cwe
	}
	return nil
}

func (x *Vulnerability) GetCvssVector() string {
	if x != nil {
		return x.CvssVector
	}
	return ""
}

func (x *Vulnerability) GetCvssScore() float64 {
	if x != nil {
		return x.CvssScore
	}
	return 0
}

func (x *Vulnerability) GetAttackVector() string {
	if x != nil {
		return x.AttackVector
	}
	return ""
}

func (x *Vulnerability) GetExploitability() string {
	if x != nil {
		return x.Exploitability
	}
	return ""
}

type Reference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{13}
}

func (x *Reference) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Reference) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Reference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SourceRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Provider       string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Scanner        string                 `protobuf:"bytes,2,opt,name=scanner,proto3" json:"scanner,omitempty"`
	ScannerVersion string                 `protobuf:"bytes,3,opt,name=scanner_version,json=scannerVersion,proto3" json:"scanner_version,omitempty"`
	FindingId      string                 `protobuf:"bytes,4,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	RunId          string                 `protobuf:"bytes,5,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SourceRecord) Reset() {
	*x = SourceRecord{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRecord) ProtoMessage() {}

func (x *SourceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRecord.ProtoReflect.Descriptor instead.
func (*SourceRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{14}
}

func (x *SourceRecord) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SourceRecord) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

func (x *SourceRecord) GetScannerVersion() string {
	if x != nil {
		return x.ScannerVersion
	}
	return ""
}

func (x *SourceRecord) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

func (x *SourceRecord) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DedupKey      string                 `protobuf:"bytes,1,opt,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"`
	NaturalKey    string                 `protobuf:"bytes,2,opt,name=natural_key,json=naturalKey,proto3" json:"natural_key,omitempty"`
	FingerprintV1 string                 `protobuf:"bytes,3,opt,name=fingerprint_v1,json=fingerprintV1,proto3" json:"fingerprint_v1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{15}
}

func (x *Identity) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

func (x *Identity) GetNaturalKey() string {
	if x != nil {
		return x.NaturalKey
	}
	return ""
}

func (x *Identity) GetFingerprintV1() string {
	if x != nil {
		return x.FingerprintV1
	}
	return ""
}

type RootCauseHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootCauseHint) Reset() {
	*x = RootCauseHint{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootCauseHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootCauseHint) ProtoMessage() {}

func (x *RootCauseHint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootCauseHint.ProtoReflect.Descriptor instead.
func (*RootCauseHint) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{16}
}

func (x *RootCauseHint) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RootCauseHint) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RootCauseHint) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RootCauseCluster struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key            string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	FindingIds     []string               `protobuf:"bytes,5,rep,name=finding_ids,json=findingIds,proto3" json:"finding_ids,omitempty"`
	Representative *Finding               `protobuf:"bytes,6,opt,name=representative,proto3" json:"representative,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RootCauseCluster) Reset() {
	*x = RootCauseCluster{}
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootCauseCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootCauseCluster) ProtoMessage() {}

func (x *RootCauseCluster) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_axon_v1_evidence_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootCauseCluster.ProtoReflect.Descriptor instead.
func (*RootCauseCluster) Descriptor() ([]byte, []int) {
	return file_api_proto_axon_v1_evidence_proto_rawDescGZIP(), []int{17}
}

func (x *RootCauseCluster) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RootCauseCluster) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RootCauseCluster) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RootCauseCluster) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RootCauseCluster) GetFindingIds() []string {
	if x != nil {
		return x.FindingIds
	}
	return nil
}

func (x *RootCauseCluster) GetRepresentative() *Finding {
	if x != nil {
		return x.Representative
	}
	return nil
}

var File_api_proto_axon_v1_evidence_proto protoreflect.FileDescriptor

const file_api_proto_axon_v1_evidence_proto_rawDesc = "" +
	"\n" +
	" api/proto/axon/v1/evidence.proto\x12\aaxon.v1\"\xa0\x02\n" +
	"\bDocument\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12!\n" +
	"\fgenerated_at\x18\x02 \x01(\tR\vgeneratedAt\x121\n" +
	"\x06source\x18\x03 \x01(\v2\x19.axon.v1.SourceDescriptorR\x06source\x12*\n" +
	"\asummary\x18\x04 \x01(\v2\x10.axon.v1.SummaryR\asummary\x12,\n" +
	"\bfindings\x18\x05 \x03(\v2\x10.axon.v1.FindingR\bfindings\x12=\n" +
	"\fcorrelations\x18\x06 \x03(\v2\x19.axon.v1.RootCauseClusterR\fcorrelations\"\x8a\x01\n" +
	"\aSummary\x12%\n" +
	"\x0etotal_findings\x18\x01 \x01(\x04R\rtotalFindings\x12'\n" +
	"\x0funique_findings\x18\x02 \x01(\x04R\x0euniqueFindings\x12/\n" +
	"\x13correlated_findings\x18\x03 \x01(\x04R\x12correlatedFindings\"\xe2\x01\n" +
	"\x10SourceDescriptor\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12!\n" +
	"\ftool_version\x18\x03 \x01(\tR\vtoolVersion\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12%\n" +
	"\x0eformat_version\x18\x05 \x01(\tR\rformatVersion\x12\x10\n" +
	"\x03uri\x18\x06 \x01(\tR\x03uri\x12!\n" +
	"\fgenerated_at\x18\a \x01(\tR\vgeneratedAt\"\xf6\b\n" +
	"\aFinding\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12-\n" +
	"\bseverity\x18\x06 \x01(\v2\x11.axon.v1.SeverityR\bseverity\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\tR\n" +
	"confidence\x12!\n" +
	"\x04rule\x18\b \x01(\v2\r.axon.v1.RuleR\x04rule\x12<\n" +
	"\x10primary_location\x18\t \x01(\v2\x11.axon.v1.LocationR\x0fprimaryLocation\x12/\n" +
	"\tlocations\x18\n" +
	" \x03(\v2\x11.axon.v1.LocationR\tlocations\x12-\n" +
	"\bartifact\x18\v \x01(\v2\x11.axon.v1.ArtifactR\bartifact\x12*\n" +
	"\apackage\x18\f \x01(\v2\x10.axon.v1.PackageR\apackage\x12$\n" +
	"\x05image\x18\r \x01(\v2\x0e.axon.v1.ImageR\x05image\x12,\n" +
	"\x05cloud\x18\x0e \x01(\v2\x16.axon.v1.CloudResourceR\x05cloud\x12'\n" +
	"\x06secret\x18\x0f \x01(\v2\x0f.axon.v1.SecretR\x06secret\x12<\n" +
	"\rvulnerability\x18\x10 \x01(\v2\x16.axon.v1.VulnerabilityR\rvulnerability\x122\n" +
	"\n" +
	"references\x18\x11 \x03(\v2\x12.axon.v1.ReferenceR\n" +
	"references\x12\x12\n" +
	"\x04tags\x18\x12 \x03(\tR\x04tags\x12-\n" +
	"\x06source\x18\x13 \x01(\v2\x15.axon.v1.SourceRecordR\x06source\x12-\n" +
	"\bidentity\x18\x14 \x01(\v2\x11.axon.v1.IdentityR\bidentity\x12@\n" +
	"\x10root_cause_hints\x18\x15 \x03(\v2\x16.axon.v1.RootCauseHintR\x0erootCauseHints\x12C\n" +
	"\vannotations\x18\x16 \x03(\v2!.axon.v1.Finding.AnnotationsEntryR\vannotations\x12*\n" +
	"\x11first_observed_at\x18\x17 \x01(\tR\x0ffirstObservedAt\x12(\n" +
	"\x10last_observed_at\x18\x18 \x01(\tR\x0elastObservedAt\x12.\n" +
	"\x13raw_record_checksum\x18\x19 \x01(\tR\x11rawRecordChecksum\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\bSeverity\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x16\n" +
	"\x06vector\x18\x03 \x01(\tR\x06vector\"h\n" +
	"\x04Rule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vsubcategory\x18\x04 \x01(\tR\vsubcategory\"\xa9\x01\n" +
	"\bLocation\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x12\n" +
	"\x04line\x18\x02 \x01(\rR\x04line\x12\x16\n" +
	"\x06column\x18\x03 \x01(\rR\x06column\x12\x19\n" +
	"\bend_line\x18\x04 \x01(\rR\aendLine\x12\x1d\n" +
	"\n" +
	"end_column\x18\x05 \x01(\rR\tendColumn\x12%\n" +
	"\x0esnippet_digest\x18\x06 \x01(\tR\rsnippetDigest\"j\n" +
	"\bArtifact\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xd8\x01\n" +
	"\aPackage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12#\n" +
	"\rfixed_version\x18\x04 \x01(\tR\ffixedVersion\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12\x1f\n" +
	"\vpackage_url\x18\x06 \x01(\tR\n" +
	"packageUrl\x12)\n" +
	"\x10dependency_chain\x18\a \x03(\tR\x0fdependencyChain\"\xab\x01\n" +
	"\x05Image\x12\x1a\n" +
	"\bregistry\x18\x01 \x01(\tR\bregistry\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\x12\x1f\n" +
	"\vbase_digest\x18\x05 \x01(\tR\n" +
	"baseDigest\x12\x1b\n" +
	"\tbase_name\x18\x06 \x01(\tR\bbaseName\"\xc0\x01\n" +
	"\rCloudResource\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x1f\n" +
	"\vresource_id\x18\x05 \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\fresource_arn\x18\x06 \x01(\tR\vresourceArn\"v\n" +
	"\x06Secret\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12 \n" +
	"\vfingerprint\x18\x03 \x01(\tR\vfingerprint\x12\x1a\n" +
	"\bredacted\x18\x04 \x01(\tR\bredacted\"\xd8\x01\n" +
	"\rVulnerability\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaliases\x18\x02 \x03(\tR\aaliases\x12\x10\n" +
	"\x03cwe\x18\x03 \x03(\tR\x03cwe\x12\x1f\n" +
	"\vcvss_vector\x18\x04 \x01(\tR\n" +
	"cvssVector\x12\x1d\n" +
	"\n" +
	"cvss_score\x18\x05 \x01(\x01R\tcvssScore\x12#\n" +
	"\rattack_vector\x18\x06 \x01(\tR\fattackVector\x12&\n" +
	"\x0eexploitability\x18\a \x01(\tR\x0eexploitability\"A\n" +
	"\tReference\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\xa3\x01\n" +
	"\fSourceRecord\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x18\n" +
	"\ascanner\x18\x02 \x01(\tR\ascanner\x12'\n" +
	"\x0fscanner_version\x18\x03 \x01(\tR\x0escannerVersion\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x04 \x01(\tR\tfindingId\x12\x15\n" +
	"\x06run_id\x18\x05 \x01(\tR\x05runId\"o\n" +
	"\bIdentity\x12\x1b\n" +
	"\tdedup_key\x18\x01 \x01(\tR\bdedupKey\x12\x1f\n" +
	"\vnatural_key\x18\x02 \x01(\tR\n" +
	"naturalKey\x12%\n" +
	"\x0efingerprint_v1\x18\x03 \x01(\tR\rfingerprintV1\"K\n" +
	"\rRootCauseHint\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xb9\x01\n" +
	"\x10RootCauseCluster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1f\n" +
	"\vfinding_ids\x18\x05 \x03(\tR\n" +
	"findingIds\x128\n" +
	"\x0erepresentative\x18\x06 \x01(\v2\x10.axon.v1.FindingR\x0erepresentativeB/Z-github.com/axon/axon/api/proto/axon/v1;axonv1b\x06proto3"

var (
	file_api_proto_axon_v1_evidence_proto_rawDescOnce sync.Once
	file_api_proto_axon_v1_evidence_proto_rawDescData []byte
)

func file_api_proto_axon_v1_evidence_proto_rawDescGZIP() []byte {
	file_api_proto_axon_v1_evidence_proto_rawDescOnce.Do(func() {
		file_api_proto_axon_v1_evidence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_axon_v1_evidence_proto_rawDesc), len(file_api_proto_axon_v1_evidence_proto_rawDesc)))
	})
	return file_api_proto_axon_v1_evidence_proto_rawDescData
}

var file_api_proto_axon_v1_evidence_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_proto_axon_v1_evidence_proto_goTypes = []any{
	(*Document)(nil),         // 0: axon.v1.Document
	(*Summary)(nil),          // 1: axon.v1.Summary
	(*SourceDescriptor)(nil), // 2: axon.v1.SourceDescriptor
	(*Finding)(nil),          // 3: axon.v1.Finding
	(*Severity)(nil),         // 4: axon.v1.Severity
	(*Rule)(nil),             // 5: axon.v1.Rule
	(*Location)(nil),         // 6: axon.v1.Location
	(*Artifact)(nil),         // 7: axon.v1.Artifact
	(*Package)(nil),          // 8: axon.v1.Package
	(*Image)(nil),            // 9: axon.v1.Image
	(*CloudResource)(nil),    // 10: axon.v1.CloudResource
	(*Secret)(nil),           // 11: axon.v1.Secret
	(*Vulnerability)(nil),    // 12: axon.v1.Vulnerability
	(*Reference)(nil),        // 13: axon.v1.Reference
	(*SourceRecord)(nil),     // 14: axon.v1.SourceRecord
	(*Identity)(nil),         // 15: axon.v1.Identity
	(*RootCauseHint)(nil),    // 16: axon.v1.RootCauseHint
	(*RootCauseCluster)(nil), // 17: axon.v1.RootCauseCluster
	nil,                      // 18: axon.v1.Finding.AnnotationsEntry
}
var file_api_proto_axon_v1_evidence_proto_depIdxs = []int32{
	2,  // 0: axon.v1.Document.source:type_name -> axon.v1.SourceDescriptor
	1,  // 1: axon.v1.Document.summary:type_name -> axon.v1.Summary
	3,  // 2: axon.v1.Document.findings:type_name -> axon.v1.Finding
	17, // 3: axon.v1.Document.correlations:type_name -> axon.v1.RootCauseCluster
	4,  // 4: axon.v1.Finding.severity:type_name -> axon.v1.Severity
	5,  // 5: axon.v1.Finding.rule:type_name -> axon.v1.Rule
	6,  // 6: axon.v1.Finding.primary_location:type_name -> axon.v1.Location
	6,  // 7: axon.v1.Finding.locations:type_name -> axon.v1.Location
	7,  // 8: axon.v1.Finding.artifact:type_name -> axon.v1.Artifact
	8,  // 9: axon.v1.Finding.package:type_name -> axon.v1.Package
	9,  // 10: axon.v1.Finding.image:type_name -> axon.v1.Image
	10, // 11: axon.v1.Finding.cloud:type_name -> axon.v1.CloudResource
	11, // 12: axon.v1.Finding.secret:type_name -> axon.v1.Secret
	12, // 13: axon.v1.Finding.vulnerability:type_name -> axon.v1.Vulnerability
	13, // 14: axon.v1.Finding.references:type_name -> axon.v1.Reference
	14, // 15: axon.v1.Finding.source:type_name -> axon.v1.SourceRecord
	15, // 16: axon.v1.Finding.identity:type_name -> axon.v1.Identity
	16, // 17: axon.v1.Finding.root_cause_hints:type_name -> axon.v1.RootCauseHint
	18, // 18: axon.v1.Finding.annotations:type_name -> axon.v1.Finding.AnnotationsEntry
	3,  // 19: axon.v1.RootCauseCluster.representative:type_name -> axon.v1.Finding
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_api_proto_axon_v1_evidence_proto_init() }
func file_api_proto_axon_v1_evidence_proto_init() {
	if File_api_proto_axon_v1_evidence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_axon_v1_evidence_proto_rawDesc), len(file_api_proto_axon_v1_evidence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_axon_v1_evidence_proto_goTypes,
		DependencyIndexes: file_api_proto_axon_v1_evidence_proto_depIdxs,
		MessageInfos:      file_api_proto_axon_v1_evidence_proto_msgTypes,
	}.Build()
	File_api_proto_axon_v1_evidence_proto = out.File
	file_api_proto_axon_v1_evidence_proto_goTypes = nil
	file_api_proto_axon_v1_evidence_proto_depIdxs = nil
}
